spring.application.name=user-management-system
server.port=8089

spring.data.mongodb.uri=<YOUR_MONGODB_CONNECTION_STRING>
spring.data.mongodb.database=user_management

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework.web=DEBUG
logging.level.com.anirudh.user_management_system=DEBUG
logging.level.org.springframework=TRACE