spring.application.name=user-management-system
server.port=8089
spring.data.mongodb.uri=mongodb+srv://anirudhgadhar2004_db_user:RADHAKRISHNA@cluster0.5yhazil.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=user_management
# Show detailed error messages in terminal
server.error.include-message=always
server.error.include-binding-errors=always

# Enable debug logging for Spring Web and your package
logging.level.org.springframework.web=DEBUG
logging.level.com.anirudh.user_management_system=DEBUG

# If you want to see full stack traces
logging.level.org.springframework=TRACE

##iPA6efO5mkUmPXw5
##anirudhgadhar2004_db_user